#!/usr/bin/env python
# -*- indent-tabs-mode: t -*-

# Imports and inits Soya.

import sys, os, os.path, soya, soya.sphere
import cerealizer
from CursorCamera import ControlledCamera
from GitOverrides import *

soya.init("git3k by Luc Banda", 1024, 780, 0)
soya.path.append(os.path.join(os.path.dirname(sys.argv[0]), "data"))


# Creates a camera.

display = soya.World()
camera = ControlledCamera(display)
camera.back = 1000.0

camera.set_xyz(7.0, 17.0, 30.0)

# Creates a light.

light = soya.Light(display)
light.set_xyz(100000.0, 100000.0, 100000.0)

Repo3D(display, '.', camera, 0.0)


soya.set_root_widget(camera)

soya.MainLoop(display).main_loop()
