#!/usr/bin/env python
# -*- indent-tabs-mode: t -*-

# Git3k is 3D visualisation of git history
# Copyright (C) 2012  <Luc Banda>
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.


# Imports and inits Soya.

import sys, os, os.path, soya, soya.gui
import cerealizer
from CursorCamera import ControlledCamera
from GitOverrides import *

soya.init("git3k", 1024, 780, 0)
soya.path.append(os.path.join(os.path.dirname(sys.argv[0]), "data"))


# Creates a camera.
display = soya.World()
camera = ControlledCamera(display, soya.Point(display, 0.0,0.0,0.0))

camera.back = 1000.0
# create a Gui
root  = soya.gui.RootLayer(None)

# Creates a light.

light = soya.Light(display)
light.set_xyz(100000.0, 100000.0, 100000.0)

#window = soya.gui.Window(root, u"Camera demo")
layer = soya.gui.Layer(root)
	
#layer = soya.gui.Layer(root)

soya.gui.CameraViewport(layer, camera)

display_text = soya.gui.Text(layer, u"", color = (1.0, 1.0, 1.0, 1.0), font = soya.Font(os.path.join(soya.DATADIR, "FreeSans.ttf"), 15, 15))
display_text.move(500,500)

camera.set_text_displayer(display_text)

repo = Repo3D(display, '.', 0.0)

camera.set_xyz(repo.head3d.x, repo.head3d.y, 30.0)


soya.set_root_widget(root)

soya.MainLoop(display).main_loop()
